{% set name = "tudat-sofa" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ../../
#  git_rev: aaf8afe3fdf16be1da09612d7e71f169605d0703
#  git_url: https://github.com/ggarrett13/sofa.git

requirements:
    build:
        - cmake
        - {{ compiler('c') }}              # [not win]
        - m2w64-gcc                        # [win]
#        - vs2017_{{ target_platform  }}    # [win]

outputs:
  - name: "{{ name }}"
    files:
      - lib/libsofa*{{ SHLIB_EXT }}   # [not win]
      - lib/libsofa.so.*              # [linux]
      - lib/libsofa.*.dylib           # [osx]
      - Library/bin/sofa.dll          # [win]
      - include/sofa            # [not win]
      - lib/cmake/sofa          # [not win]
      - Library/include/sofa    # [win]
      - Library/lib/sofa.lib    # [win]
      - Library/lib/cmake/sofa  # [win]

about:
  home: https://github.com/ggarrett13/sofa
  license: BSD
  license_family: BSD
  summary: Standards of Fundamental Astronomy code, copyright of the Board of the International Astronomical Union.
