version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  win64_m2w64gcc_build:
        executor:
          name: win/default
          shell: powershell.exe
        steps:
          - checkout
          - run: systeminfo
          - run:
              name: Build and test
              shell: powershell.exe
              # https://discuss.circleci.com/t/windows-build-with-cmake/34652
              command: |
                $ProgressPreference = "SilentlyContinue"
                Invoke-WebRequest -URI https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-win64-x64.zip -OutFile $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip
                Expand-Archive $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip -DestinationPath "$Env:ProgramFiles"
                Rename-Item "$Env:ProgramFiles\cmake-3.16.4-win64-x64" -NewName CMake
                mkdir install_test
                $LIBRARY_PREFIX = "$(pwd)/install_test"
                mkdir build
                cd build
                cmake ^
                    -G "Visual Studio 16 2019" ^
                    -DCMAKE_CXX_STANDARD=17 ^
                    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
                    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
                    -DCMAKE_BUILD_TYPE=Release ^
                    ..
                cmake --build . --config RelWithDebInfo --target install
                ctest

  linux64_gcc7_build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            mkdir install_test
            export PREFIX=$(pwd)/install_test
            bash .circleci/conda.recipe/build.sh

#      - run:
#          name: Install and test
#          command: |
#            conda install --use-local tudatpy
#            python -c 'from tudatpy import constants; print(constants.SPEED_OF_LIGHT)'
#      - store_artifacts:
#          path: /opt/conda/conda-bld/linux-64/
#          destination: /linux-64

workflows:
  version: 2.1
  win64:
    jobs:
      - win64_m2w64gcc_build
  linux64:
    jobs:
      - linux64_gcc7_build
